name: Distribute GitHub Release

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  CD:
    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - name: Prepare Env
      run: |
        sudo xcode-select -s "/Applications/Xcode_12.2.app"
        pod install
        npm install --global create-dmg

    - name: Manage Version
      run: |
        git fetch --prune --unshallow --tags
        GIT_SHA="$(git rev-parse --short HEAD)"
        CUR_TAG="$(git tag -l | grep 'alpha\|beta' | tail -1)"
        eval $(grep -m 1 "MARKETING_VERSION =" PrismUI.xcodeproj/project.pbxproj | tr -d ';' | tr -d '\t' | tr -d " ")
        if [[ "$(git log -1 --pretty=format:%s)" != *"GH Release"* ]]; then
          /usr/libexec/PlistBuddy -c "Set CFBundleVersion ${MARKETING_VERSION}-alpha-${GIT_SHA}" PrismUI/Info.plist
        fi
        echo "VER=$MARKETING_VERSION" >> $GITHUB_ENV 
        echo "SHORT_SHA=$GIT_SHA" >> $GITHUB_ENV 
        if [[ -z $CUR_TAG ]]; then
          echo "OLD_PRE_TAG=NULL" >> $GITHUB_ENV 
        else
          echo "OLD_PRE_TAG=$CUR_TAG" >> $GITHUB_ENV 
        fi

      shell: zsh {0}

    - name: Xcode Build
      run: |
        xcodebuild -workspace PrismUI.xcworkspace -scheme PrismUI -configuration Release -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}

    - name: Create Disk Image
      run: |
        XCBUILD_PATH="build/Build/Products/Release"
        cp LICENSE $XCBUILD_PATH
        cd $XCBUILD_PATH
        mv LICENSE LICENSE.txt
        create-dmg PrismUI.app || true
        mv *.dmg PrismUI.dmg
        cd -
        mkdir Artifacts
        cp -R ${XCBUILD_PATH}/*.dmg Artifacts

    - name: Setup Prerelease Variables
      if: github.event_name == 'push'
      run: |
        echo "REL_TAG=v${VER}-alpha" >> $GITHUB_ENV
        echo "IS_PRE=true" >> $GITHUB_ENV

    - name: Setup Release Variables
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "REL_TAG=v${VER}" >> $GITHUB_ENV
        echo "IS_PRE=false" >> $GITHUB_ENV
  
    - name: Generate Prerelease Release Notes
      if: github.event_name == 'push'
      run: |
        echo '### Disclaimer:' >> ReleaseNotes.md
        echo '***This alpha version is for testing only.***' >> ReleaseNotes.md
        echo 'It is not ready for daily use and we do not guarantee its usability.' >> ReleaseNotes.md
        echo 'If you discovered an issue and you do not have debugging skills, please check with the [Gitter Chat Room](https://gitter.im/ErrorErrorError/PrismUI) in advance before opening an Issue.' >> ReleaseNotes.md
  
    - name: Generate Release Notes
      run: |
        echo '### The latest updates are:' >> ReleaseNotes.md
        git log -n 5 --pretty=format:'- %H %s' | sed '/^$/d' >> ReleaseNotes.md  

    - name: Delete Old Prerelease
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        tag_name: ${{ env.OLD_PRE_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Init GitHub Release
      if: github.event_name == 'workflow_dispatch'
      uses: ncipollo/release-action@v1
      with:
        bodyFile: ReleaseNotes.md
        tag: ${{ env.REL_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Sparkle Appcast
      if: contains(github.event.head_commit.message, 'GH release')
      run: |
        mkdir sparkle
        cd sparkle
        rawURL="https://github.com/sparkle-project/Sparkle/releases/latest"
        URL="https://github.com$(one=${"$(curl -L --silent "${rawURL}" | grep '/download/' | grep -m 1 'xz' )"#*href=\"} && two=${one%\"\ rel*} && echo $two)"
        curl -#LO "${URL}"
        tar xvf *.xz >/dev/null 2>&1
        cd ..
        PUBDATE="$(date +"%a, %d %b %Y %T %z")"
        APPCAST=(
            '<?xml version="1.0" standalone="yes"?>'
            '<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">'
            '    <channel>'
            '        <title>PrismUI</title>'
            '        <item>'
            "            <title>${VER}</title>"
            "            <pubDate>${PUBDATE}</pubDate>"
            '            <description><![CDATA['
            "                <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Primer/14.4.0/primer.min.css\"><meta charset=\"UTF-8\"> $(curl -L --silent https://github.com/ErrorErrorError/PrismUI/releases/latest | sed -n '/<div class=\"markdown-body\">/,/<\/div>/p' | tr -d '\n')"
            '            ]]>'
            '            </description>'
            "            <sparkle:minimumSystemVersion>10.12</sparkle:minimumSystemVersion>"
            "            <enclosure url=\"https://PrismUI.dev/https://github.com/ErrorErrorError/PrismUI/releases/latest/download/PrismUI.dmg\" sparkle:version=\"${VER}\" sparkle:shortVersionString=\"${VER}\" type=\"application/octet-stream\" $(./sparkle/bin/sign_update -s ${SPARKLE_KEY} ./Artifacts/PrismUI.dmg)/>"
            '        </item>'
            '    </channel>'
            '</rss>'
        )
        for appcast in "${APPCAST[@]}"; do
            echo "${appcast}" >> ./Artifacts/appcast.xml
        done
      shell: bash
      env:
        SPARKLE_KEY: ${{ secrets.SPARKLE_KEY }}

    - name: Publish GitHub Release
      if: contains(github.event.head_commit.message, 'Bump version') == false
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        replacesArtifacts: true
        prerelease: ${{ env.IS_PRE }}
        bodyFile: ReleaseNotes.md
        artifacts: "./Artifacts/*"
        tag: ${{ env.REL_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
