name: Build and Test

on: 
  - push
  - pull_request

jobs:
  CI:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - name: Prepare Env
      run: |
        sudo xcode-select -s "/Applications/Xcode_12.2.app"
        pod install        

    - name: Debug Build
      run: |
        xcodebuild -workspace PrismUI.xcworkspace -scheme PrismUI -configuration Debug -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
