name: Build and Test

on: 
  - push
  - pull_request

jobs:
  CI:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Prepare Env
      run: |
        pod install
    - name: Check Strings
      run: |
        for file (./PrismUI/Appearance/**/*.strings) {
          plutil -lint $file
          if [[ $file != *"zh-Hans"* ]]; then
            grep -Hn "：" $file >> /tmp/chnCol.txt
          fi
        }
        echo ""
        if [[ $(cat /tmp/chnCol.txt) != "" ]]; then
          echo "ERROR!!! Chinese Colon\"：\" exists in:"
          echo ""
          cat /tmp/chnCol.txt
          exit 1
        fi
      shell: bash

    - name: Debug Build
      run: |
        xcodebuild -workspace PrismUI.xcworkspace -scheme PrismUI -configuration Debug -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
